---
title: "Sample 1-6 CARE Analysis - Outliers"
author: "Kaylee Delgado"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include = FALSE}

library(tidyverse)
library(jsonlite)
library(conflicted)
conflicts_prefer(dplyr::select)
```


```{r directory}

#set working directory 
data_base_dir <- "/Users/kayleedelgado/Desktop/Vaske Lab:Treehouse/Dry Lab/thops549-muscle-vs-gtex-2024sept3-NEW/Sample_1-6_CARE_Analysis"
json4_files <- tibble(file_name = list.files(path = data_base_dir,
                                            pattern = "*4.0.json", #pull 4.0json files from each sample
                                            recursive = TRUE)) %>%
  mutate(full_file_path = file.path(data_base_dir, file_name),
         TH_id = str_extract(file_name, "TH[R]?[0-9]{2}_[0-9]{4}_S[0-9]{2}")) #extract THID from sample file

```

# import json contents
```{r import data}

#import outlier data from json files
json4_contents <- json4_files %>%
  mutate(full_json_contents = map(full_file_path, fromJSON))

```

```{r}

outliers <- NULL

#check for nof1_disease_outliers in "personalized outliers", print "... are present" or "... are NOT present"
for (i in 1:nrow(json4_contents)) {
  # i=12
  print(i)
  these_outliers <- json4_contents$full_json_contents[[i]]["personalized_outliers"]$personalized_outliers
  if ("nof1_disease_outliers" %in% names(these_outliers)) {
    if ("down" %in% names(these_outliers$nof1_disease_outliers) & 
        ! is_empty(these_outliers$nof1_disease_outliers$down)) {
      print("nof1 disease down outliers are present")    
      outliers <- bind_rows(
        outliers,
        tibble(direction = "down", gene = these_outliers$nof1_disease_outliers$down) %>%
        mutate(TH_id = json4_contents$TH_id[i]))
    } else {
      print ("nof1 disease down outliers are NOT present")    
    }
    if ("nof1_disease_outliers" %in% names(these_outliers)) {
      if ("up" %in% names(these_outliers$nof1_disease_outliers) & 
        ! is_empty(these_outliers$nof1_disease_outliers$up)) {
        print("nof1 disease up outliers are present")    
        outliers <- bind_rows(
          outliers,
          tibble(direction = "up", gene = these_outliers$nof1_disease_outliers$up) %>% #create tibble to show results
          mutate(TH_id = json4_contents$TH_id[i])) 
      } else {
        print ("nof1 disease up outliers are NOT present")    
      }
    }
  }
}
```

```{r outliers}

#print outliers with THID, direction, gene
outliers %>%
  group_by(TH_id, direction, gene) %>%
  summarize(
    n_outliers = n()
  )
write_tsv(outliers, file = "Sample 1-6 nof1 Outlier Results") #save as tsv file
```

```{r recurrent outliers}

#find outliers that are recurrent among 6 samples
conflicts_prefer(dplyr::filter)

recurrent_up_outliers <- outliers %>%
  filter(direction == 'up') %>%
  group_by(`gene`) %>%
  summarize(
    Count = n(),
    TH_IDs = paste(TH_id, collapse = ", ")
  ) %>%
  filter(Count > 1) %>% #filter for outliers present in 2+ samples (ie >1) 
  arrange(desc(Count)) #arrange in descending count

print(recurrent_up_outliers)
```

```{r recurrent down outliers}

#repeate above steps for down outliers
recurrent_down_outliers <- outliers %>%
  filter(direction == 'down') %>%
  group_by(`gene`) %>%
  summarize(
    Count = n(),
    TH_IDs = paste(TH_id, collapse = ", ")
  ) %>%
  filter(Count > 1) %>%
  arrange(desc(Count))

print(recurrent_down_outliers)
```



```{r compare to variants}

conflicts_prefer(dplyr::filter)

#read in tsv file with unsolved NMD case info
mutations <- read_tsv("Unsolved Neuromuscular diseases sample info - Mutations 1-6.tsv") %>%
  fill(Fay_id, TH_id) #make difference clear between UCSF ID and UCSC THID

mutations_in_outliers <- left_join(mutations, #join outliers together with variants
          outliers %>% mutate(outlier = TRUE),
          by = c("gene", "TH_id")) #print gene name and THID

mutations_in_outliers %>%
  filter(! is.na(outlier))
```

